name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Show Xcode Environment
        run: |
          xcodebuild -version
          xcrun simctl list runtimes
          xcrun simctl list devices available

      - name: Show Build Settings
        run: |
          cd iosApp
          xcodebuild \
            -project iosApp.xcodeproj \
            -scheme iosApp \
            -showBuildSettings | grep IPHONEOS_DEPLOYMENT_TARGET

      - name: Show SDK
        run: |
          cd iosApp
          xcodebuild \
            -project iosApp.xcodeproj \
            -scheme iosApp \
            -showBuildSettings | egrep "IPHONEOS_DEPLOYMENT_TARGET|SDKROOT"

      - name: Build KMP Framework
        run: |
          ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64 --stacktrace --info

      - name: Build iOS
        run: |
          cd iosApp
          
          xcodebuild build \
            -project iosApp.xcodeproj \
            -scheme iosApp \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5'

      - name: Test iOS
        run: |
          cd iosApp
          
          xcodebuild test \
            -project iosApp.xcodeproj \
            -scheme iosApp \
            -destination 'platform=iOS Simulator,name=iPhone 16'
